import { lazy } from "react";
import type { ToolDefinition } from "../types/tool";

export const tools = [
  {
    slug: "media-transcoder",
    name: "Media Transcoder",
    summary: "Convert, trim, and compress audio or video locally.",
    category: "Media",
    capabilities: ["crossOriginIsolated"],
    component: lazy(() => import("./media-transcoder")),
  },
  {
    slug: "file-converter",
    name: "File Converter",
    summary: "Convert image, document, and data formats in your browser.",
    category: "Documents",
    component: lazy(() => import("./file-converter")),
  },
  {
    slug: "sqlite-analyzer",
    name: "SQLite Analyzer",
    summary: "Explore local CSV, JSON, and SQLite datasets.",
    category: "Data",
    capabilities: ["crossOriginIsolated"],
    component: lazy(() => import("./sqlite-analyzer")),
  },
  {
    slug: "image-optimizer",
    name: "Image Optimizer",
    summary: "Compress images and prepare reusable web assets.",
    category: "Media",
    component: lazy(() => import("./image-optimizer")),
  },
  {
    slug: "devtools-studio",
    name: "DevTools Studio",
    summary: "Format, inspect, and transform code or structured text.",
    category: "Developer",
    component: lazy(() => import("./devtools-studio")),
  },
  {
    slug: "document-redliner",
    name: "Document Redliner",
    summary: "Compare local contracts and resumes without uploading them.",
    category: "Documents",
    component: lazy(() => import("./document-redliner")),
  },
  {
    slug: "offline-transcriber",
    name: "Offline Transcriber",
    summary: "Transcribe local meeting and podcast recordings.",
    category: "Media",
    capabilities: ["crossOriginIsolated"],
    component: lazy(() => import("./offline-transcriber")),
  },
  {
    slug: "secrets-vault",
    name: "Secrets Vault",
    summary: "Keep encrypted credentials in a portable local vault.",
    category: "Security",
    capabilities: ["fileSystemAccess"],
    component: lazy(() => import("./secrets-vault")),
  },
  {
    slug: "financial-anonymizer",
    name: "Financial Anonymizer",
    summary: "Redact sensitive fields in financial documents.",
    category: "Documents",
    component: lazy(() => import("./financial-anonymizer")),
  },
  {
    slug: "spreadsheet-api-mocker",
    name: "Spreadsheet API Mocker",
    summary: "Turn local spreadsheet rows into a test API.",
    category: "Developer",
    component: lazy(() => import("./spreadsheet-api-mocker")),
  },
  {
    slug: "artifact-inspector",
    name: "Artifact Inspector",
    summary: "Inspect local binaries and files with security rules.",
    category: "Security",
    capabilities: ["crossOriginIsolated"],
    component: lazy(() => import("./artifact-inspector")),
  },
  {
    slug: "leak-scanner",
    name: "Secret and PII Scanner",
    summary: "Find exposed credentials and personal data in local files.",
    category: "Security",
    component: lazy(() => import("./leak-scanner")),
  },
  {
    slug: "yara-playground",
    name: "YARA Playground",
    summary: "Write, test, and profile YARA rules locally.",
    category: "Security",
    capabilities: ["crossOriginIsolated"],
    component: lazy(() => import("./yara-playground")),
  },
  {
    slug: "compliance-gatekeeper",
    name: "Compliance Gatekeeper",
    summary: "Check email and documents before they are shared.",
    category: "Security",
    component: lazy(() => import("./compliance-gatekeeper")),
  },
  {
    slug: "font-specimen",
    name: "Font Specimen",
    summary: "Preview local fonts and export type scale tokens.",
    category: "Design",
    component: lazy(() => import("./font-specimen")),
  },
  {
    slug: "pii-scrubber",
    name: "Spreadsheet PII Scrubber",
    summary: "Remove personal data from CSV and spreadsheet files.",
    category: "Data",
    component: lazy(() => import("./pii-scrubber")),
  },
  {
    slug: "metadata-scrubber",
    name: "Photo Metadata Scrubber",
    summary: "Remove location metadata and rename photos in batches.",
    category: "Media",
    component: lazy(() => import("./metadata-scrubber")),
  },
  {
    slug: "log-pattern-extractor",
    name: "Log Pattern Extractor",
    summary: "Detect useful structures in logs and export clean data.",
    category: "Developer",
    component: lazy(() => import("./log-pattern-extractor")),
  },
  {
    slug: "audio-editor",
    name: "Audio Editor",
    summary: "Trim, normalize, and clean up local audio.",
    category: "Media",
    capabilities: ["webCodecs"],
    component: lazy(() => import("./audio-editor")),
  },
  {
    slug: "barcode-labeler",
    name: "Barcode Labeler",
    summary: "Generate printable barcode and QR label sheets.",
    category: "Data",
    component: lazy(() => import("./barcode-labeler")),
  },
  {
    slug: "structural-diff",
    name: "Structural Diff",
    summary: "Compare and merge JSON, YAML, or XML by structure.",
    category: "Developer",
    component: lazy(() => import("./structural-diff")),
  },
  {
    slug: "palette-checker",
    name: "Palette and Contrast",
    summary: "Extract colors and check accessible contrast.",
    category: "Design",
    component: lazy(() => import("./palette-checker")),
  },
  {
    slug: "batch-converter",
    name: "Batch Converter",
    summary: "Convert units, currencies, and time zones in spreadsheets.",
    category: "Data",
    component: lazy(() => import("./batch-converter")),
  },
] as const satisfies readonly ToolDefinition[];

export function getTool(slug: string): ToolDefinition | undefined {
  return tools.find((tool) => tool.slug === slug);
}
